# Generated by Django 6.1.1 on 2026-10-05 07:26

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CaptchaChallenge',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('challenge_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('captcha_text', models.CharField(max_length=16)),
                ('options', models.JSONField(default=list)),
                ('correct_option', models.CharField(max_length=16)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('VERIFIED', 'Verified'), ('CLAIMED', 'Claimed'), ('DISMISSED', 'Dismissed'), ('EXPIRED', 'Expired')], db_index=True, default='PENDING', max_length=20)),
                ('expires_at', models.DateTimeField(db_index=True)),
                ('selected_option', models.CharField(blank=True, max_length=16, null=True)),
                ('result', models.CharField(blank=True, choices=[('CORRECT', 'Correct'), ('WRONG', 'Wrong'), ('EXPIRED', 'Expired')], max_length=20, null=True)),
                ('reward_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('reward_status', models.CharField(choices=[('PENDING', 'Pending'), ('CREDITED', 'Credited')], default='PENDING', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='captcha_challenges', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'CAPTCHA Challenge',
                'verbose_name_plural': 'CAPTCHA Challenges',
                'db_table': 'captcha_challenge',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CaptchaAttempt',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('selected_option', models.CharField(max_length=16)),
                ('result', models.CharField(max_length=20)),
                ('reward', models.DecimalField(decimal_places=2, max_digits=14)),
                ('status', models.CharField(max_length=20)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='captcha_attempts', to=settings.AUTH_USER_MODEL)),
                ('challenge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='captcha.captchachallenge')),
            ],
            options={
                'verbose_name': 'CAPTCHA Attempt',
                'verbose_name_plural': 'CAPTCHA Attempts',
                'db_table': 'captcha_attempt',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='captchachallenge',
            index=models.Index(fields=['user', 'status', 'expires_at'], name='captcha_cha_user_id_e45098_idx'),
        ),
        migrations.AddIndex(
            model_name='captchaattempt',
            index=models.Index(fields=['user', '-created_at'], name='captcha_att_user_id_c33e34_idx'),
        ),
        migrations.AddIndex(
            model_name='captchaattempt',
            index=models.Index(fields=['challenge', '-created_at'], name='captcha_att_challen_0edc64_idx'),
        ),
    ]
