# Generated by Django 6.1.1 on 2026-10-05 07:13

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('gems', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('ves', models.BigIntegerField(default=0)),
                ('sves', models.BigIntegerField(default=0)),
                ('tokens', models.BigIntegerField(default=0)),
                ('spins', models.BigIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='wallet', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Wallet',
                'verbose_name_plural': 'Wallets',
                'db_table': 'wallets_wallet',
            },
        ),
        migrations.CreateModel(
            name='WalletTransaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('transaction_id', models.CharField(db_index=True, editable=False, max_length=64, unique=True)),
                ('currency', models.CharField(choices=[('GEM', 'Gems'), ('VE', 'VEs'), ('SVE', 'SVEs'), ('TOKEN', 'Tokens'), ('SPIN', 'Spins')], max_length=10)),
                ('direction', models.CharField(choices=[('CREDIT', 'Credit'), ('DEBIT', 'Debit')], max_length=10)),
                ('type', models.CharField(choices=[('CAPTCHA_REWARD', 'Captcha Reward'), ('REWARD', 'Reward'), ('BONUS', 'Bonus'), ('DAILY_REWARD', 'Daily Reward'), ('AD_REWARD', 'Ad Reward'), ('GAME_REWARD', 'Game Reward'), ('REFERRAL', 'Referral'), ('ADMIN_CREDIT', 'Admin Credit'), ('ADMIN_DEBIT', 'Admin Debit'), ('CORRECTION', 'Correction'), ('EXCHANGE_CREDIT', 'Exchange Credit'), ('EXCHANGE_DEBIT', 'Exchange Debit'), ('WITHDRAWAL', 'Withdrawal'), ('WITHDRAWAL_REVERSAL', 'Withdrawal Reversal')], max_length=50)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('balance_before', models.DecimalField(decimal_places=2, max_digits=14)),
                ('balance_after', models.DecimalField(decimal_places=2, max_digits=14)),
                ('source', models.CharField(default='SYSTEM', max_length=50)),
                ('reference_id', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('status', models.CharField(choices=[('COMPLETED', 'Completed'), ('REVERSED', 'Reversed'), ('PENDING', 'Pending')], default='COMPLETED', max_length=20)),
                ('description', models.CharField(blank=True, max_length=500, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to=settings.AUTH_USER_MODEL)),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='wallets.wallet')),
            ],
            options={
                'verbose_name': 'Wallet Transaction',
                'verbose_name_plural': 'Wallet Transactions',
                'db_table': 'wallets_transaction',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='wallets_tra_user_id_7ea3e7_idx'), models.Index(fields=['wallet', '-created_at'], name='wallets_tra_wallet__ec3627_idx')],
            },
        ),
    ]
